/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package junittesteclipse;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void lars() {
        assertTrue(true, "someLibraryMethod should return 'true'");
    }
}
