/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.vogella.prioritizer.bugzilla.model;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.Test;

class LibraryTest {
    @Test void testSomeLibraryMethod() {
        assertTrue(true, "someLibraryMethod should return 'true'");
    }
}